package com.example.projectcalculator.model;

import java.time.LocalDate;

/**
 * Represents a project in the Project Calculator application.
 *
 * <p>A project is a container for tasks, resources, and other project-related data.
 * Each project has a unique identifier, name, description, and deadline.</p>
 *
 * <p><b>Example Usage:</b></p>
 * <pre>
 * Project project = new Project(1L, "Website Redesign", "Redesign company website", LocalDate.of(2024, 12, 31));
 * project.setDescription("Complete overhaul of the main company website");
 * </pre>
 *
 * @author Magnus & Arian
 * @version 1.0
 * @since 1.0
 * @see LocalDate
 */
public class Project {

    /** Unique identifier for the project. Typically auto-generated by the persistence layer. */
    private Long id;

    /** The name of the project. Must be non-null and non-empty. */
    private String name;

    /** Detailed description of the project objectives and scope. */
    private String description;

    /** The target completion date for the project. */
    private LocalDate deadline;

    /**
     * Calculates the total estimated hours for all tasks within this project.
     *
     * <p>This method aggregates the estimated hours from all tasks associated
     * with this project. The current implementation returns {@code null} and
     * should be overridden with actual logic.</p>
     *
     * @return the total estimated hours for all project tasks, or {@code null}
     *         if no tasks exist or the calculation cannot be performed
     */
    public Double getTotalEstimatedHours() {
        return null;
    }

    /**
     * Default constructor. Creates a new, uninitialized Project instance.
     *
     * <p>Use this constructor when creating a project that will be populated
     * via setter methods or form binding.</p>
     */
    public Project() {
    }

    /**
     * Creates a fully initialized Project instance with all required fields.
     *
     * @param id the unique identifier for the project
     * @param name the name of the project (must not be {@code null} or empty)
     * @param description a detailed description of the project
     * @param deadline the target completion date for the project
     *
     * @throws IllegalArgumentException if {@code name} is {@code null} or empty
     * @throws NullPointerException if {@code deadline} is {@code null}
     */
    public Project(Long id, String name, String description, LocalDate deadline) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.deadline = deadline;
    }

    /**
     * Returns the unique identifier of this project.
     *
     * @return the project's unique identifier, or {@code null} if not set
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for this project.
     *
     * @param id the unique identifier to assign to this project
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the name of this project.
     *
     * @return the project name, or {@code null} if not set
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name for this project.
     *
     * @param name the project name (must not be {@code null} or empty)
     * @throws IllegalArgumentException if {@code name} is {@code null} or empty
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description of this project.
     *
     * @return the project description, or {@code null} if not set
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description for this project.
     *
     * @param description a detailed description of the project
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the deadline (target completion date) for this project.
     *
     * @return the project deadline, or {@code null} if not set
     */
    public LocalDate getDeadline() {
        return deadline;
    }

    /**
     * Sets the deadline (target completion date) for this project.
     *
     * @param deadline the target completion date for the project
     * @throws NullPointerException if {@code deadline} is {@code null}
     */
    public void setDeadline(LocalDate deadline) {
        this.deadline = deadline;
    }
}