package com.example.projectcalculator.model;

import java.time.LocalDate;
import java.util.List;

/**
 * Represents a sub-project within a larger project in the Project Calculator application.
 *
 * <p>A sub-project is a component or phase of a main project that can have its own
 * tasks, deadlines, and deliverables. Sub-projects help in organizing complex projects
 * into manageable sections.</p>
 *
 * <p><b>Note:</b> This class currently accepts a {@code List<Task>} parameter in its
 * constructor but does not store it. Consider adding a tasks field if task management
 * functionality is required.</p>
 *
 * <p><b>Example Usage:</b></p>
 * <pre>
 * SubProject subProject = new SubProject(1L, "UI Design", "Design user interface components",
 *                                         LocalDate.of(2024, 6, 30), new ArrayList<>());
 * subProject.setDescription("Design all UI components for the dashboard");
 * </pre>
 *
 * @author Magnus
 * @version 1.0
 * @since 1.0
 * @see Project
 * @see LocalDate
 * @see Task
 */
public class SubProject {

    /** Unique identifier for the sub-project. Typically auto-generated by the persistence layer. */
    private Long id;

    /** The name of the sub-project. Must be non-null and non-empty. */
    private String name;

    /** Detailed description of the sub-project objectives and scope. */
    private String description;

    /** The target completion date for this sub-project component. */
    private LocalDate deadline;

    // Note: The constructor accepts a List<Task> parameter but doesn't store it.
    // Consider adding: private List<Task> tasks; if needed.

    /**
     * Default constructor. Creates a new, uninitialized SubProject instance.
     *
     * <p>Use this constructor when creating a sub-project that will be populated
     * via setter methods or form binding.</p>
     */
    public SubProject() {
    }

    /**
     * Creates a fully initialized SubProject instance with all required fields.
     *
     * <p><b>Note:</b> The {@code tasks} parameter is accepted but not stored in
     * the current implementation. Consider adding a tasks field if needed.</p>
     *
     * @param id the unique identifier for the sub-project
     * @param name the name of the sub-project (must not be {@code null} or empty)
     * @param description a detailed description of the sub-project
     * @param deadline the target completion date for the sub-project
     * @param tasks the list of tasks associated with this sub-project (currently unused)
     *
     * @throws IllegalArgumentException if {@code name} is {@code null} or empty
     * @throws NullPointerException if {@code deadline} is {@code null}
     */
    public SubProject(Long id, String name, String description, LocalDate deadline, List<Task> tasks) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.deadline = deadline;
        // Note: tasks parameter is not stored. Consider implementing task management.
    }

    /**
     * Returns the unique identifier of this sub-project.
     *
     * @return the sub-project's unique identifier, or {@code null} if not set
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for this sub-project.
     *
     * @param id the unique identifier to assign to this sub-project
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the name of this sub-project.
     *
     * @return the sub-project name, or {@code null} if not set
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name for this sub-project.
     *
     * @param name the sub-project name (must not be {@code null} or empty)
     * @throws IllegalArgumentException if {@code name} is {@code null} or empty
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description of this sub-project.
     *
     * @return the sub-project description, or {@code null} if not set
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description for this sub-project.
     *
     * @param description a detailed description of the sub-project
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the deadline (target completion date) for this sub-project.
     *
     * @return the sub-project deadline, or {@code null} if not set
     */
    public LocalDate getDeadline() {
        return deadline;
    }

    /**
     * Sets the deadline (target completion date) for this sub-project.
     *
     * @param deadline the target completion date for the sub-project
     * @throws NullPointerException if {@code deadline} is {@code null}
     */
    public void setDeadline(LocalDate deadline) {
        this.deadline = deadline;
    }
}