package com.example.projectcalculator.model;

import java.time.LocalDate;

/**
 * Represents a task within a sub-project in the Project Calculator application.
 *
 * <p>A task is the smallest unit of work in the project hierarchy, containing
 * specific work items that need to be completed. Each task is associated with
 * a sub-project, has an estimated duration, and a target completion date.</p>
 *
 * <p><b>Example Usage:</b></p>
 * <pre>
 * Task task = new Task(1L, 101L, "Design Login Screen",
 *                      "Create wireframes and mockups for login interface",
 *                      LocalDate.of(2024, 5, 15), 8.5);
 * task.setEstimatedHours(10.0);
 * </pre>
 *
 * @author Daniel
 * @version 1.0
 * @since 1.0
 * @see SubProject
 * @see LocalDate
 */
public class Task {

    /** Unique identifier for the task. Typically auto-generated by the persistence layer. */
    private Long id;

    /** Identifier of the parent sub-project to which this task belongs. */
    private Long subProjectId;

    /** The name of the task. Must be non-null and non-empty. */
    private String name;

    /** Detailed description of the task requirements and deliverables. */
    private String description;

    /** The target completion date for this specific task. */
    private LocalDate deadline;

    /** The estimated number of hours required to complete this task. Must be non-negative. */
    private Double estimatedHours;

    /**
     * Default constructor. Creates a new, uninitialized Task instance.
     *
     * <p>Use this constructor when creating a task that will be populated
     * via setter methods or form binding.</p>
     */
    public Task() {}

    /**
     * Creates a fully initialized Task instance with all required fields.
     *
     * @param id the unique identifier for the task
     * @param subProjectId the identifier of the parent sub-project
     * @param name the name of the task (must not be {@code null} or empty)
     * @param description a detailed description of the task
     * @param deadline the target completion date for the task
     * @param estimatedHours the estimated hours required to complete the task (must be non-negative)
     *
     * @throws IllegalArgumentException if {@code name} is {@code null} or empty,
     *                                  or if {@code estimatedHours} is negative
     * @throws NullPointerException if {@code deadline} is {@code null}
     */
    public Task(Long id, Long subProjectId, String name,
                String description, LocalDate deadline, Double estimatedHours) {
        this.id = id;
        this.subProjectId = subProjectId;
        this.name = name;
        this.description = description;
        this.deadline = deadline;
        this.estimatedHours = estimatedHours;
    }

    /**
     * Returns the unique identifier of this task.
     *
     * @return the task's unique identifier, or {@code null} if not set
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier for this task.
     *
     * @param id the unique identifier to assign to this task
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the identifier of the parent sub-project.
     *
     * @return the parent sub-project identifier, or {@code null} if not associated
     */
    public Long getSubProjectId() {
        return subProjectId;
    }

    /**
     * Sets the parent sub-project identifier for this task.
     *
     * @param subProjectId the identifier of the parent sub-project
     */
    public void setSubProjectId(Long subProjectId) {
        this.subProjectId = subProjectId;
    }

    /**
     * Returns the name of this task.
     *
     * @return the task name, or {@code null} if not set
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name for this task.
     *
     * @param name the task name (must not be {@code null} or empty)
     * @throws IllegalArgumentException if {@code name} is {@code null} or empty
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description of this task.
     *
     * @return the task description, or {@code null} if not set
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description for this task.
     *
     * @param description a detailed description of the task
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the deadline (target completion date) for this task.
     *
     * @return the task deadline, or {@code null} if not set
     */
    public LocalDate getDeadline() {
        return deadline;
    }

    /**
     * Sets the deadline (target completion date) for this task.
     *
     * @param deadline the target completion date for the task
     * @throws NullPointerException if {@code deadline} is {@code null}
     */
    public void setDeadline(LocalDate deadline) {
        this.deadline = deadline;
    }

    /**
     * Returns the estimated hours required to complete this task.
     *
     * @return the estimated hours, or {@code null} if not set
     */
    public Double getEstimatedHours() {
        return estimatedHours;
    }

    /**
     * Sets the estimated hours required to complete this task.
     *
     * @param estimatedHours the estimated hours (must be non-negative)
     * @throws IllegalArgumentException if {@code estimatedHours} is negative
     */
    public void setEstimatedHours(Double estimatedHours) {
        this.estimatedHours = estimatedHours;
    }
}