package com.example.projectcalculator.repository;

import com.example.projectcalculator.model.Project;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;

/**
 * Repository class for managing {@link Project} entities in the database.
 *
 * <p>This repository provides CRUD (Create, Read, Delete) operations for Project entities
 * using Spring's {@link JdbcTemplate}. It serves as the data access layer between
 * the application and the underlying database.</p>
 *
 * <p><b>Note:</b> This class contains duplicate methods:
 * <ul>
 *   <li>{@link #create(Project)} and {@link #createProject(Project)} perform identical operations</li>
 *   <li>{@link #delete(long)} and {@link #deleteProject(long)} perform identical operations</li>
 * </ul>
 * Consider consolidating these methods for maintainability.</p>
 *
 * <p><b>Example Usage:</b></p>
 * <pre>
 * // Creating a project
 * Project project = new Project(null, "New Website", "Build company website", LocalDate.now().plusMonths(3));
 * boolean created = projectRepository.create(project);
 *
 * // Finding all projects
 * List<Project> projects = projectRepository.findAllProjects();
 *
 * // Deleting a project
 * boolean deleted = projectRepository.deleteProject(1L);
 * </pre>
 *
 * @author Arian, Daniel & Magnus
 * @version 1.0
 * @since 1.0
 * @see Project
 * @see JdbcTemplate
 * @see Repository
 */
@Repository
public class ProjectRepository {

    /** JDBC template for executing SQL operations against the database. */
    private final JdbcTemplate jdbcTemplate;

    /**
     * Constructs a new ProjectRepository with the specified JdbcTemplate.
     *
     * @param jdbcTemplate the JdbcTemplate to use for database operations
     * @throws NullPointerException if {@code jdbcTemplate} is {@code null}
     */
    public ProjectRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Creates a new project in the database.
     *
     * <p>This method inserts a new project record into the "project" table.
     * The ID is typically auto-generated by the database.</p>
     *
     * <p><b>Note:</b> This method is functionally identical to {@link #createProject(Project)}.</p>
     *
     * @param project the project to create (must not be {@code null})
     * @return {@code true} if the project was successfully created (at least one row affected),
     *         {@code false} otherwise
     * @throws NullPointerException if {@code project} is {@code null}
     * @throws org.springframework.dao.DataAccessException if a database access error occurs
     */
    public boolean create(Project project) {
        String sql = """
                INSERT INTO project (name, description, deadline)
                VALUES (?, ?, ?)
                """;

        int rows = jdbcTemplate.update(
                sql,
                project.getName(),
                project.getDescription(),
                project.getDeadline()
        );

        return rows > 0;
    }

    /**
     * Retrieves all projects from the database, ordered by their ID.
     *
     * @return a list of all projects in the database, ordered by ID;
     *         returns an empty list if no projects exist
     * @throws org.springframework.dao.DataAccessException if a database access error occurs
     */
    public List<Project> findAllProjects() {
        String sql = """
                SELECT id, name, description, deadline
                FROM project
                ORDER BY id
                """;
        return jdbcTemplate.query(sql, new ProjectRowMapper());
    }

    /**
     * Creates a new project in the database.
     *
     * <p>This method inserts a new project record into the "project" table.
     * The ID is typically auto-generated by the database.</p>
     *
     * <p><b>Note:</b> This method is functionally identical to {@link #create(Project)}.</p>
     *
     * @param project the project to create (must not be {@code null})
     * @return {@code true} if the project was successfully created (at least one row affected),
     *         {@code false} otherwise
     * @throws NullPointerException if {@code project} is {@code null}
     * @throws org.springframework.dao.DataAccessException if a database access error occurs
     */
    public boolean createProject(Project project) {
        String sql = "INSERT INTO project (name, description, deadline) VALUES (?, ?, ?)";
        int rows = jdbcTemplate.update(
                sql,
                project.getName(),
                project.getDescription(),
                project.getDeadline()
        );
        return rows > 0;
    }

    /**
     * Deletes a project from the database by its ID.
     *
     * <p><b>Note:</b> This method is functionally identical to {@link #delete(long)}.</p>
     *
     * @param id the ID of the project to delete
     * @return {@code true} if the project was successfully deleted (at least one row affected),
     *         {@code false} if no project with the given ID exists
     * @throws org.springframework.dao.DataAccessException if a database access error occurs
     */
    public boolean deleteProject(long id) {
        String sql = "DELETE FROM project WHERE id = ?";
        int rows = jdbcTemplate.update(sql, id);
        return rows > 0;
    }

    /**
     * Deletes a project from the database by its ID.
     *
     * <p><b>Note:</b> This method is functionally identical to {@link #deleteProject(long)}.</p>
     *
     * @param id the ID of the project to delete
     * @return {@code true} if the project was successfully deleted (at least one row affected),
     *         {@code false} if no project with the given ID exists
     * @throws org.springframework.dao.DataAccessException if a database access error occurs
     */
    public boolean delete(long id) {
        String sql = "DELETE FROM project WHERE id = ?";
        int rows = jdbcTemplate.update(sql, id);
        return rows > 0;
    }

    /**
     * RowMapper implementation for converting ResultSet rows into {@link Project} objects.
     *
     * <p>This inner class handles the mapping of database result set rows to Project
     * entity objects. It extracts values from the ResultSet and constructs a new
     * Project instance.</p>
     *
     * @see RowMapper
     * @see ResultSet
     */
    private static class ProjectRowMapper implements RowMapper<Project> {

        /**
         * Maps a row of the ResultSet to a Project object.
         *
         * @param rs the ResultSet to map (must be positioned on a valid row)
         * @param rowNum the number of the current row (0-indexed)
         * @return a new Project instance populated with data from the ResultSet
         * @throws SQLException if a database access error occurs or column values cannot be retrieved
         */
        @Override
        public Project mapRow(ResultSet rs, int rowNum) throws SQLException {
            Long id = rs.getLong("id");
            String name = rs.getString("name");
            String description = rs.getString("description");
            LocalDate deadline = rs.getDate("deadline") != null
                    ? rs.getDate("deadline").toLocalDate()
                    : null;
            return new Project(id, name, description, deadline);
        }
    }
}


/*
 rows = antal rækker påvirket af SQL-operationen.
 rows > 0  → en række blev slettet/opdateret
 rows == 0 → ingen rækker matchede betingelsen (fx ID findes ikke).

 Returner ikke rows > 0? boolean = false
*/

